name: XFCE noVNC LocalTunnel

on:
  workflow_dispatch:

jobs:
  desktop:
    runs-on: ubuntu-latest

    steps:
      - name: Update system
        run: sudo apt update

      - name: Install XFCE VNC noVNC
        run: |
          sudo apt install -y xfce4 xfce4-goodies tigervnc-standalone-server novnc websockify nodejs npm

          mkdir -p ~/.vnc
          echo "1" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd

          vncserver -kill :1 || true
          vncserver -geometry 1600x900 :1

          nohup websockify --web=/usr/share/novnc 6080 localhost:5901 >/dev/null 2>&1 &

      - name: Install LocalTunnel
        run: sudo npm install -g localtunnel

      - name: Start LocalTunnel
        run: |
          nohup lt --port 6080 > tunnel.log 2>&1 &
          sleep 10

          echo "Tunnel URL:"
          grep -o 'https://[a-zA-Z0-9.-]*\.loca\.lt' tunnel.log | head -n 1

      - name: Show tunnel log
        run: cat tunnel.log

      - name: Keep runner alive
        run: sleep 21600
